// create table view data object
	// Ti.API.info(record);
	var imageUrlHeadString = 'http://thechive.files.wordpress.com/2010/01/hot-chive-hotties-';
	var likeIcon           = '/images/liked.png';
	var noLikeIcon         = '/images/noLiked.png';
		// create table view data object
	var shopData = [
		{title:'Unknown Store', 	shopId:0,		addr:'Unknown',					city:'Unknown',			lati:0,				lon:0},
		{title:'Macy\'s', 			shopId:1,		addr:'3165 Kifer Rd',			city:'Santa Clara',		lati:0,				lon:0},
		{title:'一麻一辣', 			shopId:2,		addr:'1234 Qianmen Street',		city:'Beijing',			lati:39.97168911,	lon:116.51696264521209},	
		{title:'上岛咖啡', 			shopId:3,		addr:'333 Gulou Street',		city:'Santa Clara',		lati:39.93168911,	lon:116.52696264521209},
		{title:'我型你秀', 			shopId:4,		addr:'1234 Qianmen Street',		city:'Beijing',			lati:39.94168911,	lon:116.53696264521209},	
		{title:'Macy\'s', 			shopId:5,		addr:'333 Gulou Street',		city:'Santa Clara',		lati:0,				lon:0},
		];
		
		
	var data = [
		{title:'Alan', 		liked:0,		likeCount:0,		picHeight:200,	hasChild:true, 	header:'A'},
		{title:'Alice', 	liked:0,		likeCount:0,		picHeight:300,	hasDetail:true},
		{title:'Alexander',	liked:0,		likeCount:0,		picHeight:400},
		{title:'Amos',		liked:0,		likeCount:0,		picHeight:200},
		{title:'Alonzo',	liked:0,		likeCount:0,		picHeight:300},
		{title:'Brad',		liked:0,		likeCount:0,		picHeight:400, 	header:'B'},
		{title:'Brent',		liked:0,		likeCount:0,		picHeight:200},
		{title:'Billy',		liked:0,		likeCount:0,		picHeight:300},
		{title:'Brenda',	liked:0,		likeCount:0,		picHeight:400},
		{title:'Callie',					header:'C'},
		{title:'Cassie'},
		{title:'Chris'},
		{title:'Cameron'},
		{title:'Don', header:'D'},
		{title:'Dilbert'},
		{title:'Deacon'},
		{title:'Devin'},
		{title:'Darin'},
		{title:'Darcy'},
		{title:'Erin', header:'E'},
		{title:'Erica'},
		{title:'Elvin'},
		{title:'Edrick'},
		{title:'Frank', header:'F'},
		{title:'Fred'},
		{title:'Fran'},
		{title:'Felicity'},
		{title:'George', header:'G'},
		{title:'Gina'},
		{title:'Gary'},
		{title:'Herbert', header:'H'},
		{title:'Henry'},
		{title:'Harold'},
		{title:'Ignatius', header:'I'},
		{title:'Irving'},
		{title:'Ivan'},
		{title:'Dr. J', header:'J'},
		{title:'Jefferson'},
		{title:'Jenkins'},
		{title:'Judy'},
		{title:'Julie'},
		{title:'Kristy', header:'K'},
		{title:'Krusty the Clown'},
		{title:'Klaus'},
		{title:'Larry', header:'L'},
		{title:'Leon'},
		{title:'Lucy'},
		{title:'Ludwig'},
		{title:'Mary', header:'M'},
		{title:'Mervin'},
		{title:'Malcom'},
		{title:'Mellon'},
		{title:'Ned', header:'N'},
		{title:'Nervous Eddie'},
		{title:'Nelson'},
		{title:'The Big O', header:'O'},
		{title:'Orlando'},
		{title:'Ox'},
		{title:'Pluto', header:'P'},
		{title:'Paris'},
		{title:'Potsie'}
	];